# Generated by Django 5.2.1 on 2025-06-25 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Optional weight limit in kilograms', max_digits=5, null=True)),
                ('age_limit', models.IntegerField(blank=True, help_text='Optional age limit in years', null=True)),
                ('additional_rules', models.TextField(blank=True, help_text='Optional additional rules for the group', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='api.group'),
        ),
    ]
