# Generated by Django 5.2.1 on 2025-05-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='athletes',
        ),
        migrations.DeleteModel(
            name='CategoryTeam',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
