# Generated by Django 5.2.1 on 2025-06-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_category_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='additional_rules',
        ),
        migrations.RemoveField(
            model_name='group',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='weight_limit',
        ),
    ]
