# Generated by Django 5.2.1 on 2025-05-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_category_teams_remove_team_athletes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='athletes',
        ),
        migrations.DeleteModel(
            name='AthleteCategory',
        ),
    ]
