# Generated by Django 5.2.1 on 2025-05-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_category_athletes_delete_athletecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='api.athlete'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('athletes', models.ManyToManyField(related_name='teams', to='api.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='categories', through='api.CategoryTeam', to='api.team'),
        ),
    ]
