# Generated by Django 5.2.1 on 2025-06-25 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_group_additional_rules_remove_group_age_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='groups',
        ),
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='api.group'),
        ),
    ]
