# Generated by Django 5.2.1 on 2025-06-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_category_groups_category_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='group',
            name='category',
        ),
        migrations.AddField(
            model_name='group',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='groups', to='api.category'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
