# Generated by Django 5.2.1 on 2025-05-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_athletes_team_categoryteam_category_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'teams'}, related_name='team_categories', through='api.CategoryTeam', to='api.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='category_teams', through='api.CategoryTeam', to='api.team'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryteam',
            unique_together={('category', 'team')},
        ),
    ]
