# Generated by Django 5.2.1 on 2025-06-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_category_groups_remove_group_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='api.group'),
        ),
    ]
