# Generated by Django 5.2.1 on 2025-06-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_group_categories_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.competition'),
            preserve_default=False,
        ),
    ]
