# Generated by Django 5.2.1 on 2025-08-27 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('social_media_facebook', models.URLField(blank=True)),
                ('social_media_instagram', models.URLField(blank=True)),
                ('social_media_twitter', models.URLField(blank=True)),
                ('business_hours', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['order', 'section_title'], 'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Post', 'verbose_name_plural': 'News Posts'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for staff'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the event'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='External registration link'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspost',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which sections appear'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description for previews', max_length=300),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title', unique=True),
        ),
    ]
