# Generated by Django 5.2.1 on 2025-08-27 09:57

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contactinfo_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for image (SEO)', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content'),
        ),
        migrations.AddField(
            model_name='event',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (160 chars max)', max_length=160),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, separated by commas', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max). If empty, uses the main title.', max_length=60),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page'),
        ),
        migrations.AddField(
            model_name='event',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='default-slug', help_text='URL-friendly version of the title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separated by commas', max_length=255),
        ),
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newspost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=100),
        ),
        migrations.AddField(
            model_name='newspost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (160 chars max)', max_length=160),
        ),
        migrations.AddField(
            model_name='newspost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, separated by commas', max_length=255),
        ),
        migrations.AddField(
            model_name='newspost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max). If empty, uses the main title.', max_length=60),
        ),
        migrations.AddField(
            model_name='newspost',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separated by commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='business_hours',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Business Hours'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='excerpt',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Excerpt'),
        ),
    ]
